services:
  shairport-sync:
    container_name: shairport-sync
    image: rohmilkaese/shairport-sync:latest
    volumes:
      - ./conf/shairport.conf:/conf/shairport.conf
    devices:
      - /dev/snd
    command: -vu -c /conf/shairport.conf
    network_mode: "host"
